# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfejs.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 427)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.action_picker = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action_picker.sizePolicy().hasHeightForWidth())
        self.action_picker.setSizePolicy(sizePolicy)
        self.action_picker.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.action_picker.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.action_picker.setObjectName("action_picker")
        self.tab_welcome = QtWidgets.QWidget()
        self.tab_welcome.setObjectName("tab_welcome")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_welcome)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_welcome)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.tab_welcome)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.action_picker.addTab(self.tab_welcome, "")
        self.tab_check_volume = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_check_volume.sizePolicy().hasHeightForWidth())
        self.tab_check_volume.setSizePolicy(sizePolicy)
        self.tab_check_volume.setObjectName("tab_check_volume")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_check_volume)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab_check_volume)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.layout_autovolume_pick_file = QtWidgets.QHBoxLayout()
        self.layout_autovolume_pick_file.setObjectName("layout_autovolume_pick_file")
        self.edit_autovolume_file_name = QtWidgets.QLineEdit(self.tab_check_volume)
        self.edit_autovolume_file_name.setEnabled(False)
        self.edit_autovolume_file_name.setObjectName("edit_autovolume_file_name")
        self.layout_autovolume_pick_file.addWidget(self.edit_autovolume_file_name)
        self.button_autovolume_pick_file = QtWidgets.QPushButton(self.tab_check_volume)
        self.button_autovolume_pick_file.setAcceptDrops(True)
        self.button_autovolume_pick_file.setObjectName("button_autovolume_pick_file")
        self.layout_autovolume_pick_file.addWidget(self.button_autovolume_pick_file)
        self.verticalLayout_2.addLayout(self.layout_autovolume_pick_file)
        self.layout_check_volume_run = QtWidgets.QHBoxLayout()
        self.layout_check_volume_run.setObjectName("layout_check_volume_run")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_check_volume_run.addItem(spacerItem1)
        self.button_check_volume_run = QtWidgets.QPushButton(self.tab_check_volume)
        self.button_check_volume_run.setObjectName("button_check_volume_run")
        self.layout_check_volume_run.addWidget(self.button_check_volume_run)
        self.verticalLayout_2.addLayout(self.layout_check_volume_run)
        self.layout_volume_output = QtWidgets.QHBoxLayout()
        self.layout_volume_output.setObjectName("layout_volume_output")
        self.label_volume_output = QtWidgets.QLabel(self.tab_check_volume)
        self.label_volume_output.setObjectName("label_volume_output")
        self.layout_volume_output.addWidget(self.label_volume_output)
        self.spin_volume_output = QtWidgets.QSpinBox(self.tab_check_volume)
        self.spin_volume_output.setEnabled(False)
        self.spin_volume_output.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_volume_output.setMinimum(-2147483647)
        self.spin_volume_output.setMaximum(2147483647)
        self.spin_volume_output.setObjectName("spin_volume_output")
        self.layout_volume_output.addWidget(self.spin_volume_output)
        self.verticalLayout_2.addLayout(self.layout_volume_output)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.button_update_split_volume = QtWidgets.QPushButton(self.tab_check_volume)
        self.button_update_split_volume.setEnabled(False)
        self.button_update_split_volume.setObjectName("button_update_split_volume")
        self.horizontalLayout_2.addWidget(self.button_update_split_volume)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.layout_next_steps = QtWidgets.QHBoxLayout()
        self.layout_next_steps.setObjectName("layout_next_steps")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_next_steps.addItem(spacerItem4)
        self.lebel_next_step = QtWidgets.QLabel(self.tab_check_volume)
        self.lebel_next_step.setObjectName("lebel_next_step")
        self.layout_next_steps.addWidget(self.lebel_next_step)
        self.button_next_step = QtWidgets.QPushButton(self.tab_check_volume)
        self.button_next_step.setObjectName("button_next_step")
        self.layout_next_steps.addWidget(self.button_next_step)
        self.button_next_step2 = QtWidgets.QPushButton(self.tab_check_volume)
        self.button_next_step2.setObjectName("button_next_step2")
        self.layout_next_steps.addWidget(self.button_next_step2)
        self.verticalLayout_2.addLayout(self.layout_next_steps)
        self.action_picker.addTab(self.tab_check_volume, "")
        self.tab_split_channels = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_split_channels.sizePolicy().hasHeightForWidth())
        self.tab_split_channels.setSizePolicy(sizePolicy)
        self.tab_split_channels.setObjectName("tab_split_channels")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_split_channels)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab_split_channels)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.listview_split_channels_files = QtWidgets.QListView(self.tab_split_channels)
        self.listview_split_channels_files.setMaximumSize(QtCore.QSize(16777215, 150))
        self.listview_split_channels_files.setAcceptDrops(True)
        self.listview_split_channels_files.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listview_split_channels_files.setAlternatingRowColors(True)
        self.listview_split_channels_files.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listview_split_channels_files.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listview_split_channels_files.setObjectName("listview_split_channels_files")
        self.verticalLayout_6.addWidget(self.listview_split_channels_files)
        self.layout_split_add_2 = QtWidgets.QHBoxLayout()
        self.layout_split_add_2.setObjectName("layout_split_add_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_split_add_2.addItem(spacerItem5)
        self.button_split_channels_pick_file = QtWidgets.QPushButton(self.tab_split_channels)
        self.button_split_channels_pick_file.setObjectName("button_split_channels_pick_file")
        self.layout_split_add_2.addWidget(self.button_split_channels_pick_file)
        self.button_split_channels_delete_picked_file = QtWidgets.QPushButton(self.tab_split_channels)
        self.button_split_channels_delete_picked_file.setObjectName("button_split_channels_delete_picked_file")
        self.layout_split_add_2.addWidget(self.button_split_channels_delete_picked_file)
        self.verticalLayout_6.addLayout(self.layout_split_add_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_split_channels_accept = QtWidgets.QPushButton(self.tab_split_channels)
        self.button_split_channels_accept.setObjectName("button_split_channels_accept")
        self.horizontalLayout_6.addWidget(self.button_split_channels_accept)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.action_picker.addTab(self.tab_split_channels, "")
        self.tab_split_action = QtWidgets.QWidget()
        self.tab_split_action.setObjectName("tab_split_action")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_split_action)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tab_split_action)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.layout_volume = QtWidgets.QVBoxLayout()
        self.layout_volume.setObjectName("layout_volume")
        self.volume_label = QtWidgets.QLabel(self.tab_split_action)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.volume_label.setFont(font)
        self.volume_label.setObjectName("volume_label")
        self.layout_volume.addWidget(self.volume_label)
        self.volume_layout = QtWidgets.QHBoxLayout()
        self.volume_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.volume_layout.setObjectName("volume_layout")
        self.slider_silence = QtWidgets.QSlider(self.tab_split_action)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_silence.sizePolicy().hasHeightForWidth())
        self.slider_silence.setSizePolicy(sizePolicy)
        self.slider_silence.setMinimum(-100)
        self.slider_silence.setMaximum(100)
        self.slider_silence.setSingleStep(5)
        self.slider_silence.setProperty("value", -30)
        self.slider_silence.setOrientation(QtCore.Qt.Horizontal)
        self.slider_silence.setInvertedAppearance(False)
        self.slider_silence.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_silence.setTickInterval(10)
        self.slider_silence.setObjectName("slider_silence")
        self.volume_layout.addWidget(self.slider_silence)
        self.spin_silence = QtWidgets.QSpinBox(self.tab_split_action)
        self.spin_silence.setMinimum(-100)
        self.spin_silence.setMaximum(100)
        self.spin_silence.setSingleStep(5)
        self.spin_silence.setProperty("value", -30)
        self.spin_silence.setObjectName("spin_silence")
        self.volume_layout.addWidget(self.spin_silence)
        self.layout_volume.addLayout(self.volume_layout)
        self.layout_from_file = QtWidgets.QHBoxLayout()
        self.layout_from_file.setObjectName("layout_from_file")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_from_file.addItem(spacerItem8)
        self.button_from_file = QtWidgets.QPushButton(self.tab_split_action)
        self.button_from_file.setObjectName("button_from_file")
        self.layout_from_file.addWidget(self.button_from_file)
        self.layout_volume.addLayout(self.layout_from_file)
        self.verticalLayout_3.addLayout(self.layout_volume)
        self.layout_silence_length = QtWidgets.QVBoxLayout()
        self.layout_silence_length.setObjectName("layout_silence_length")
        self.label_silence_length = QtWidgets.QLabel(self.tab_split_action)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_silence_length.setFont(font)
        self.label_silence_length.setObjectName("label_silence_length")
        self.layout_silence_length.addWidget(self.label_silence_length)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.slider_silence_length = QtWidgets.QSlider(self.tab_split_action)
        self.slider_silence_length.setMinimum(100)
        self.slider_silence_length.setMaximum(5000)
        self.slider_silence_length.setSingleStep(100)
        self.slider_silence_length.setPageStep(100)
        self.slider_silence_length.setProperty("value", 1000)
        self.slider_silence_length.setOrientation(QtCore.Qt.Horizontal)
        self.slider_silence_length.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_silence_length.setTickInterval(100)
        self.slider_silence_length.setObjectName("slider_silence_length")
        self.horizontalLayout_7.addWidget(self.slider_silence_length)
        self.spin_silence_length = QtWidgets.QSpinBox(self.tab_split_action)
        self.spin_silence_length.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spin_silence_length.setMinimum(100)
        self.spin_silence_length.setMaximum(10000)
        self.spin_silence_length.setSingleStep(100)
        self.spin_silence_length.setProperty("value", 1000)
        self.spin_silence_length.setObjectName("spin_silence_length")
        self.horizontalLayout_7.addWidget(self.spin_silence_length)
        self.layout_silence_length.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.layout_silence_length)
        self.layout_split_file_process = QtWidgets.QVBoxLayout()
        self.layout_split_file_process.setObjectName("layout_split_file_process")
        self.listview_split_files = QtWidgets.QListView(self.tab_split_action)
        self.listview_split_files.setMaximumSize(QtCore.QSize(16777215, 150))
        self.listview_split_files.setAcceptDrops(True)
        self.listview_split_files.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listview_split_files.setAlternatingRowColors(True)
        self.listview_split_files.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listview_split_files.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listview_split_files.setObjectName("listview_split_files")
        self.layout_split_file_process.addWidget(self.listview_split_files)
        self.layout_split_add = QtWidgets.QHBoxLayout()
        self.layout_split_add.setObjectName("layout_split_add")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_split_add.addItem(spacerItem9)
        self.button_split_pick_file = QtWidgets.QPushButton(self.tab_split_action)
        self.button_split_pick_file.setObjectName("button_split_pick_file")
        self.layout_split_add.addWidget(self.button_split_pick_file)
        self.button_delete_picked_file = QtWidgets.QPushButton(self.tab_split_action)
        self.button_delete_picked_file.setObjectName("button_delete_picked_file")
        self.layout_split_add.addWidget(self.button_delete_picked_file)
        self.layout_split_file_process.addLayout(self.layout_split_add)
        self.verticalLayout_3.addLayout(self.layout_split_file_process)
        self.layout_go = QtWidgets.QHBoxLayout()
        self.layout_go.setObjectName("layout_go")
        self.button_split_accept = QtWidgets.QPushButton(self.tab_split_action)
        self.button_split_accept.setObjectName("button_split_accept")
        self.layout_go.addWidget(self.button_split_accept)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_go.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.layout_go)
        self.action_picker.addTab(self.tab_split_action, "")
        self.tab_processing = QtWidgets.QWidget()
        self.tab_processing.setObjectName("tab_processing")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_processing)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.tab_processing)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.listview_log = QtWidgets.QListView(self.tab_processing)
        self.listview_log.setAlternatingRowColors(True)
        self.listview_log.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listview_log.setWordWrap(True)
        self.listview_log.setObjectName("listview_log")
        self.verticalLayout_5.addWidget(self.listview_log)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_back = QtWidgets.QPushButton(self.tab_processing)
        self.button_back.setEnabled(False)
        self.button_back.setObjectName("button_back")
        self.horizontalLayout_3.addWidget(self.button_back)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.action_picker.addTab(self.tab_processing, "")
        self.horizontalLayout.addWidget(self.action_picker)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.action_picker.setCurrentIndex(4)
        self.slider_silence.valueChanged['int'].connect(self.spin_silence.setValue)
        self.spin_silence.valueChanged['int'].connect(self.slider_silence.setValue)
        self.spin_silence_length.valueChanged['int'].connect(self.slider_silence_length.setValue)
        self.slider_silence_length.valueChanged['int'].connect(self.spin_silence_length.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edit_autovolume_file_name, self.button_autovolume_pick_file)
        MainWindow.setTabOrder(self.button_autovolume_pick_file, self.button_check_volume_run)
        MainWindow.setTabOrder(self.button_check_volume_run, self.button_next_step)
        MainWindow.setTabOrder(self.button_next_step, self.button_next_step2)
        MainWindow.setTabOrder(self.button_next_step2, self.button_split_channels_pick_file)
        MainWindow.setTabOrder(self.button_split_channels_pick_file, self.button_split_channels_delete_picked_file)
        MainWindow.setTabOrder(self.button_split_channels_delete_picked_file, self.listview_split_channels_files)
        MainWindow.setTabOrder(self.listview_split_channels_files, self.button_split_channels_accept)
        MainWindow.setTabOrder(self.button_split_channels_accept, self.button_split_pick_file)
        MainWindow.setTabOrder(self.button_split_pick_file, self.button_split_accept)
        MainWindow.setTabOrder(self.button_split_accept, self.listview_split_files)
        MainWindow.setTabOrder(self.listview_split_files, self.button_delete_picked_file)
        MainWindow.setTabOrder(self.button_delete_picked_file, self.slider_silence_length)
        MainWindow.setTabOrder(self.slider_silence_length, self.spin_silence_length)
        MainWindow.setTabOrder(self.spin_silence_length, self.button_update_split_volume)
        MainWindow.setTabOrder(self.button_update_split_volume, self.button_back)
        MainWindow.setTabOrder(self.button_back, self.listview_log)
        MainWindow.setTabOrder(self.listview_log, self.button_from_file)
        MainWindow.setTabOrder(self.button_from_file, self.spin_silence)
        MainWindow.setTabOrder(self.spin_silence, self.spin_volume_output)
        MainWindow.setTabOrder(self.spin_volume_output, self.slider_silence)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Witaj użytkowniku"))
        self.label_2.setText(_translate("MainWindow", "wersja testowa v0.0"))
        self.action_picker.setTabText(self.action_picker.indexOf(self.tab_welcome), _translate("MainWindow", "Witaj"))
        self.label_3.setText(_translate("MainWindow", "Dzięki tej funkcji programu możesz sprawdzić jaką głośność ma wycinek dźwięku. Jest to przydatne przy określaniu poziomu ciszy."))
        self.button_autovolume_pick_file.setText(_translate("MainWindow", "&Wybierz plik"))
        self.button_check_volume_run.setText(_translate("MainWindow", "&Sprawdź"))
        self.label_volume_output.setText(_translate("MainWindow", "Głośność:"))
        self.spin_volume_output.setSuffix(_translate("MainWindow", "dB"))
        self.button_update_split_volume.setText(_translate("MainWindow", "Ustaw jako głośność do dzielenia"))
        self.lebel_next_step.setText(_translate("MainWindow", "Następne kroki"))
        self.button_next_step.setText(_translate("MainWindow", "Podziel →"))
        self.button_next_step2.setText(_translate("MainWindow", "lub Rozdziel kanały →"))
        self.action_picker.setTabText(self.action_picker.indexOf(self.tab_check_volume), _translate("MainWindow", "Sprawdź &głośność"))
        self.label_4.setText(_translate("MainWindow", "Dzięki tej funckji programu, możesz rozdzielić kanały wielu plików za jednym razem. Jest to przydatne w przypadkach, w których na taśmie/orginale na lewym kanale jest jeden utwór, a na prawym drugi."))
        self.button_split_channels_pick_file.setText(_translate("MainWindow", "&Wybierz"))
        self.button_split_channels_delete_picked_file.setText(_translate("MainWindow", "Usuń"))
        self.button_split_channels_accept.setText(_translate("MainWindow", "&Jedziemy"))
        self.action_picker.setTabText(self.action_picker.indexOf(self.tab_split_channels), _translate("MainWindow", "Rozdziel &kanały"))
        self.label_5.setText(_translate("MainWindow", "Dzięki tej funckji programu, możesz rozdzielić wiele plików za jednym razem. Pozwala to na półautomatyczne wycięcie utworów z jednego dużego pliku."))
        self.volume_label.setText(_translate("MainWindow", "Poziom ciszy"))
        self.spin_silence.setSuffix(_translate("MainWindow", "dB"))
        self.button_from_file.setText(_translate("MainWindow", "Z &Pliku"))
        self.label_silence_length.setText(_translate("MainWindow", "Długość ciszy"))
        self.spin_silence_length.setSuffix(_translate("MainWindow", "ms"))
        self.button_split_pick_file.setText(_translate("MainWindow", "&Wybierz"))
        self.button_delete_picked_file.setText(_translate("MainWindow", "&Usuń"))
        self.button_split_accept.setText(_translate("MainWindow", "&Jedziemy"))
        self.action_picker.setTabText(self.action_picker.indexOf(self.tab_split_action), _translate("MainWindow", "&Podziel"))
        self.label_6.setText(_translate("MainWindow", "Tutaj pokazują się logi operacji, która jest właśnie przeprowadzana. Zamykanie programu nie jest polecane, raz straconego postępu nie można odzyskać i należy operacje przeprowadzić jeszcze raz."))
        self.button_back.setText(_translate("MainWindow", "← &Powrót"))
        self.action_picker.setTabText(self.action_picker.indexOf(self.tab_processing), _translate("MainWindow", "Działania"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
